apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: documenso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # NextAuth Secret
  nextauth-secret: {{ include "documenso.nextAuthSecret" . | quote }}
  # Encryption Keys
  encryption-key: {{ include "documenso.encryptionKey" . | quote }}
  encryption-secondary-key: {{ include "documenso.encryptionSecondaryKey" . | quote }}
  {{- if .Values.smtp.host }}
  # SMTP Credentials
  smtp-username: {{ .Values.smtp.username | quote }}
  smtp-password: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- if .Values.oidc.enabled }}
  # OIDC Credentials
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.s3.enabled }}
  # S3 Credentials
  s3-access-key-id: {{ .Values.s3.accessKeyId | quote }}
  s3-secret-access-key: {{ .Values.s3.secretAccessKey | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-signing
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: documenso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # Signing Certificate Password
  password: {{ include "documenso.signingPassword" . | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-env
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: documenso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  .env: |
    # Database Configuration
    #NEXT_PRIVATE_DATABASE_URL=postgresql://{{ include "documenso.database.username" . }}:$DB_PASSWORD@{{ include "documenso.database.host" . }}:{{ include "documenso.database.port" . }}/{{ include "documenso.database.name" . }}
    #NEXT_PRIVATE_DIRECT_DATABASE_URL=postgresql://{{ include "documenso.database.username" . }}:$DB_PASSWORD@{{ include "documenso.database.host" . }}:{{ include "documenso.database.port" . }}/{{ include "documenso.database.name" . }}
    POSTGRES_URL=postgresql://{{ include "documenso.database.username" . }}:$DB_PASSWORD@{{ include "documenso.database.host" . }}:{{ include "documenso.database.port" . }}/{{ include "documenso.database.name" . }}
    
    # Encryption Keys
    #NEXT_PRIVATE_ENCRYPTION_KEY={{ include "documenso.encryptionKey" . }}
    #NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY={{ include "documenso.encryptionSecondaryKey" . }}

    {{- if .Values.s3.enabled }}
    # S3 Storage Configuration
    NEXT_PRIVATE_UPLOAD_ENDPOINT={{ .Values.s3.endpoint }}
    NEXT_PRIVATE_UPLOAD_REGION={{ .Values.s3.region }}
    NEXT_PRIVATE_UPLOAD_BUCKET={{ .Values.s3.bucket }}
    NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID={{ .Values.s3.accessKeyId }}
    NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY={{ .Values.s3.secretAccessKey }}
    NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE={{ .Values.s3.forcePathStyle }}
    {{- end }}
